export const markerColors = {
  "DRUG SMUGGLING, POSSESION, SALE OR USE OF DRUGS": '#F1C40F',
  "THE GAMBLING ACT":'#B2BABB',
  "ROBBERY, THEFT, BURGLARY, DACOITY":'#D5F5E3',
  "CULPABLE HOMICIDE AND GREVIOUS HURT":'#FADBD8',
  "ROAD ACCIDENTS":'#82E0AA',
  "ABDUCTION OR KIDNAPPING":'#FCF3CF',
  "ARMS/EXPLOSIVE - RELATED ACTS":'#D98880',
  "ASSAULT":'#F8C471',
  "RAPE":'#A93226',
  "THE MINES AND MINERALS (DEVELOPMENT AND REGULATION) ACT":'#85C1E9',
  "FIRST DEGREE MURDER":'#76448A',
  "ENVIRONMENT AND POLLUTION - RELATED ACTS":'#117A65',
  "CHILD ABUSE":'#EDBB99',
  "EXTORTION AND BLACKMAIL":'#FBFCFC',
  "HUMAN TRAFFICKING":'#78281F',
  "THE IMMORAL TRAFFIC (PREVENTION) ACT":'#5F6A6A'

}

// export const intensities = {
//   "DRUG SMUGGLING, POSSESION, SALE OR USE OF DRUGS",
//   "THE GAMBLING ACT",
//   "ROBBERY, THEFT, BURGLARY, DACOITY",
//   "CULPABLE HOMICIDE AND GREVIOUS HURT",
//   "ROAD ACCIDENTS",
//   "ABDUCTION OR KIDNAPPING",
//   "ARMS/EXPLOSIVE - RELATED ACTS",
//   "ASSAULT",
//   "RAPE",
//   "THE MINES AND MINERALS (DEVELOPMENT AND REGULATION) ACT",
//   "FIRST DEGREE MURDER",
//   "ENVIRONMENT AND POLLUTION - RELATED ACTS",
//   "CHILD ABUSE",
//   "EXTORTION AND BLACKMAIL",
//   "HUMAN TRAFFICKING",
//   "THE IMMORAL TRAFFIC (PREVENTION) ACT"

// }