 export const markerColors = {
  "DRUG SMUGGLING, POSSESION, SALE OR USE OF DRUGS": '#85C1E9',
  "THE GAMBLING ACT":'#B2BABB',
  "ROBBERY, THEFT, BURGLARY, DACOITY":'#D5F5E3',
  "CULPABLE HOMICIDE AND GREVIOUS HURT":'#FADBD8',
  "ROAD ACCIDENTS":'#82E0AA',
  "ABDUCTION OR KIDNAPPING":'#FCF3CF',
  "ARMS/EXPLOSIVE - RELATED ACTS":'#D98880',
  "ASSAULT":'#F8C471',
  "RAPE":'#A93226',
  "THE MINES AND MINERALS (DEVELOPMENT AND REGULATION) ACT":'#76448A',
  "FIRST DEGREE MURDER":'#F1C40F',
  "ENVIRONMENT AND POLLUTION - RELATED ACTS":'#117A65',
  "CHILD ABUSE":'#EDBB99',
  "EXTORTION AND BLACKMAIL":'#FBFCFC',
  "HUMAN TRAFFICKING":'#78281F',
  "THE IMMORAL TRAFFIC (PREVENTION) ACT":'#5F6A6A'

}

export const intensities = {
  "DRUG SMUGGLING, POSSESION, SALE OR USE OF DRUGS":70,
  "THE GAMBLING ACT":30,
  "ROBBERY, THEFT, BURGLARY, DACOITY":30,
  "CULPABLE HOMICIDE AND GREVIOUS HURT":80,
  "ROAD ACCIDENTS":20,
  "ABDUCTION OR KIDNAPPING":50,
  "ARMS/EXPLOSIVE - RELATED ACTS":60,
  "ASSAULT":50,
  "RAPE":90,
  "THE MINES AND MINERALS (DEVELOPMENT AND REGULATION) ACT":20,
  "FIRST DEGREE MURDER":90,
  "ENVIRONMENT AND POLLUTION - RELATED ACTS":20,
  "CHILD ABUSE":100,
  "EXTORTION AND BLACKMAIL":10,
  "HUMAN TRAFFICKING":80,
  "THE IMMORAL TRAFFIC (PREVENTION) ACT":80
}