export const markerColors = {
  "DRUG SMUGGLING, POSSESION, SALE OR USE OF DRUGS": '#F1C40F',
  "THE GAMBLING ACT":'#B2BABB',
  "ROBBERY, THEFT, BURGLARY, DACOITY":'#D5F5E3',
  "CULPABLE HOMICIDE AND GREVIOUS HURT":'#FADBD8',
  "ROAD ACCIDENTS":'#82E0AA',
  "ABDUCTION OR KIDNAPPING":'#FCF3CF',
  "ARMS/EXPLOSIVE - RELATED ACTS":'#D98880',
  "ASSAULT":'#F8C471',
  "RAPE":'#A93226',
  "THE MINES AND MINERALS (DEVELOPMENT AND REGULATION) ACT":'#85C1E9',
  "FIRST DEGREE MURDER":'#76448A',
  "ENVIRONMENT AND POLLUTION - RELATED ACTS":'#117A65',
  "CHILD ABUSE":'#EDBB99',
  "EXTORTION AND BLACKMAIL":'#FBFCFC',
  "HUMAN TRAFFICKING":'#78281F',
  "THE IMMORAL TRAFFIC (PREVENTION) ACT":'#5F6A6A'

}

export const intensities = {
  "DRUG SMUGGLING, POSSESION, SALE OR USE OF DRUGS":10,
  "THE GAMBLING ACT":20,
  "ROBBERY, THEFT, BURGLARY, DACOITY":30,
  "CULPABLE HOMICIDE AND GREVIOUS HURT":40,
  "ROAD ACCIDENTS":50,
  "ABDUCTION OR KIDNAPPING":10,
  "ARMS/EXPLOSIVE - RELATED ACTS":20,
  "ASSAULT":30,
  "RAPE":20,
  "THE MINES AND MINERALS (DEVELOPMENT AND REGULATION) ACT":10,
  "FIRST DEGREE MURDER":14,
  "ENVIRONMENT AND POLLUTION - RELATED ACTS":90,
  "CHILD ABUSE":30,
  "EXTORTION AND BLACKMAIL":22,
  "HUMAN TRAFFICKING":24,
  "THE IMMORAL TRAFFIC (PREVENTION) ACT":10
}